unlock:
  name: Unlock
  description: Unlock Access
  fields:
    server_address:
      name: Server
      description: Doorlink address, such as http://192.168.1.100:8080.
      selector:
        text: {}
    sip_info:
      name: Contact
      description: Contact, such as 10019901@172.16.0.101:5060.
      required: true
      selector:
        text: {}

appoint:
  name: Appoint
  description: Elev Appoint
  fields:
    server_address:
      name: Server
      description: Doorlink address, such as http://192.168.1.100:8080.
      selector:
        text: {}
    sip_info:
      name: Contact
      description: Contact, such as 10019901@172.16.0.101:5060.
      required: true
      selector:
        text: {}
    floor:
      name: Floor
      description: Floor.
      selector:
        number:
          min: -10
          max: 99
    direct:
      name: Elev Direction
      description: Elev direction.
      required: true
      selector:
        number:
          min: 1
          max: 2

permit:
  name: Permit
  description: Elev Permit
  fields:
    server_address:
      name: Server
      description: Doorlink address, such as http://192.168.1.100:8080.
      selector:
        text: {}
    sip_info:
      name: Contact
      description: Contact, such as 10019901@172.16.0.101:5060.
      required: true
      selector:
        text: {}
    floor:
      name: Floor
      description: Floor.
      selector:
        number:
          min: -10
          max: 99

bye:
  name: Bye
  description: Hung up
  fields:
    server_address:
      name: Server
      description: Doorlink address, such as http://192.168.1.100:8080.
      selector:
        text: {}
    sip_info:
      name: Contact
      description: Contact, such as 10019901@172.16.0.101:5060.
      required: true
      selector:
        text: {}

execute:
  name: Execute
  description: Execute SIP CMD
  fields:
    server_address:
      name: Server
      description: Doorlink address, such as http://192.168.1.100:8080.
      selector:
        text: {}
    json_data:
      name: Json Data
      description: Json data, such as {}.
      required: true
      selector:
        text: {}
